window.NIGHTREIGN_MAPPING = Object.freeze({
  kings: [
    { id: "gladius", name: "グラディウス", aliases: ["三つ首の獣", "夜の獣", "ぐらでぃうす"], resistanceIds: ["gladius"] },
    { id: "edre", name: "エデレ", aliases: ["喰らいつく顎", "えでれ"], resistanceIds: ["edre"] },
    { id: "gnoster", name: "グノスター", aliases: ["知性の蟲", "知性の虫", "ぐのすたー"], resistanceIds: ["gnoster-moth", "gnoster-scorpion", "gnoster-animus"] },
    { id: "malis", name: "マリス", aliases: ["深海の夜", "まりす"], resistanceIds: ["malis"] },
    { id: "libra", name: "リブラ", aliases: ["調律の魔物", "りぶら"], resistanceIds: ["libra"] },
    { id: "fulghor", name: "フルゴール", aliases: ["闇駆ける狩人", "夜光の騎士", "ふるごーる"], resistanceIds: ["fulghor"] },
    { id: "caligo", name: "カリゴ", aliases: ["霧の裂け目", "かりご"], resistanceIds: ["caligo"] },
    { id: "nameless", name: "ナメレス", aliases: ["夜を象る者", "夜の輪郭", "なめれす"], resistanceIds: ["nameless-outline", "nameless-second"] },
    { id: "harmonia", name: "ハルモニア", aliases: ["安寧者たち", "バランサー", "はるもにあ"], resistanceIds: ["harmonia", "harmonia-everdark"] },
    { id: "strages", name: "ストラゲス", aliases: ["瓦礫の王", "すとらげす"], resistanceIds: ["strages"] }
  ],
  day1: [
    { id: "d1-demihuman-duo", name: "亜人の女王＆亜人の剣聖", aliases: ["亜人女王", "亜人の女王", "亜人の剣聖", "剣聖"], kings: ["グラディウス"], resistanceIds: ["demihuman-queen", "demihuman-swordsaint"], namelessPossible: true },
    { id: "d1-bell-bearing-hunter", name: "鈴玉狩り", aliases: ["鈴玉", "すずだまがり"], kings: ["グラディウス"], resistanceIds: ["bell-bearing-hunter"], namelessPossible: true },
    { id: "d1-devouring-dragon", name: "貪食ドラゴン", aliases: ["どんしょくドラゴン"], kings: ["エデレ", "マリス", "フルゴール"], resistanceIds: ["devouring-dragon"], namelessPossible: true },
    { id: "d1-night-cavalry", name: "夜の騎兵", aliases: ["夜騎兵", "よるのきへい"], kings: ["エデレ", "フルゴール"], resistanceIds: ["night-cavalry"], namelessPossible: true },
    { id: "d1-hero-gargoyle", name: "英雄のガーゴイル", aliases: ["ガーゴイル"], kings: ["エデレ", "マリス"], resistanceIds: ["hero-gargoyle"], namelessPossible: true },
    { id: "d1-wormface", name: "ミミズ顔", aliases: ["みみずがお", "ワームフェイス"], kings: ["エデレ", "マリス", "フルゴール"], resistanceIds: ["wormface"], namelessPossible: true },
    { id: "d1-centipede-demon", name: "百足のデーモン", aliases: ["むかで"], kings: ["グノスター", "リブラ", "フルゴール"], resistanceIds: ["centipede-demon"], namelessPossible: true },
    { id: "d1-molten-demon", name: "熔鉄デーモン", aliases: ["溶鉄デーモン", "ようてつデーモン"], kings: ["グノスター", "マリス", "カリゴ"], resistanceIds: ["molten-demon"], namelessPossible: true },
    { id: "d1-field-commander", name: "戦場の宿将", aliases: ["宿将", "しゅくしょう"], kings: ["グノスター", "リブラ"], resistanceIds: ["field-commander"], namelessPossible: true },
    { id: "d1-putrid-tree-spirit", name: "爛れた樹霊", aliases: ["樹霊", "ただれたじゅれい"], kings: ["グノスター", "カリゴ"], resistanceIds: ["putrid-tree-spirit"], namelessPossible: true },
    { id: "d1-grafted-lord", name: "接ぎ木の君主", aliases: ["接ぎ木"], kings: ["マリス", "カリゴ"], resistanceIds: ["grafted-lord"], namelessPossible: true },
    { id: "d1-tibia-mariner", name: "ティビアの呼び舟", aliases: ["ティビア", "呼び舟"], kings: ["リブラ", "グノスター", "カリゴ"], resistanceIds: ["tibia-mariner"], namelessPossible: true },
    { id: "d1-royal-revenant", name: "王族の幽鬼", aliases: ["幽鬼", "ゆうき"], kings: ["リブラ", "フルゴール"], resistanceIds: ["royal-revenant"], namelessPossible: true },
    { id: "d1-public-freyja", name: "公のフレイディア", aliases: ["フレイディア"], kings: ["エデレ", "リブラ", "カリゴ"], resistanceIds: ["public-freyja"], namelessPossible: true },
    { id: "d1-wounded-demon-duo", name: "傷ついたデーモン＆うろ底のデーモン", aliases: ["傷ついたデーモン", "うろ底のデーモン", "ハルモニア"], kings: ["ハルモニア"], resistanceIds: ["wounded-demon", "abyssal-demon"], namelessPossible: false },
    { id: "d1-curseblade-divine-warrior", name: "呪剣士＆神獣の戦士", aliases: ["呪剣士", "神獣の戦士"], kings: ["ハルモニア"], resistanceIds: ["curseblade", "divine-warrior"], namelessPossible: false },
    { id: "d1-great-red-bear", name: "大赤熊", aliases: ["赤熊", "おおあかぐま"], kings: ["ストラゲス"], resistanceIds: ["great-red-bear"], namelessPossible: false },
    { id: "d1-death-knight", name: "死の騎士", aliases: ["死騎士", "しのきし"], kings: ["ストラゲス"], resistanceIds: ["death-knight"], namelessPossible: false }
  ],
  day2: [
    { id: "d2-tree-guardian", name: "ツリーガード", aliases: ["ツリーガード", "tree guardian"], kings: ["グラディウス", "マリス"], resistanceIds: ["tree-guardian"], namelessPossible: true },
    { id: "d2-margit", name: "忌み鬼", aliases: ["いみおに", "マルギット", "モーゴット"], kings: ["グラディウス"], resistanceIds: ["margit"], namelessPossible: true },
    { id: "d2-ancient-dragon", name: "古竜", aliases: ["こりゅう"], kings: ["エデレ"], resistanceIds: ["ancient-dragon"], namelessPossible: true },
    { id: "d2-crucible-hippo", name: "坩堝の騎士＆黄金カバ", aliases: ["坩堝", "黄金カバ", "おうごんカバ"], kings: ["リブラ", "エデレ"], resistanceIds: ["crucible-knight", "golden-hippopotamus"], namelessPossible: true },
    { id: "d2-roaming-commander", name: "僻地の宿将", aliases: ["宿将", "へきち"], kings: ["エデレ", "フルゴール"], resistanceIds: ["roaming-commander"], namelessPossible: true },
    { id: "d2-nox-dragonkin", name: "ノクスの竜人兵", aliases: ["竜人兵", "のくす"], kings: ["グノスター", "フルゴール"], resistanceIds: ["nox-dragonkin"], namelessPossible: true },
    { id: "d2-dragon-tree-guardian", name: "竜のツリーガード", aliases: ["竜ツリーガード", "dragon tree sentinel"], kings: ["グノスター", "カリゴ"], resistanceIds: ["dragon-tree-guardian"], namelessPossible: true },
    { id: "d2-greatland-dragon", name: "大土竜", aliases: ["大土竜", "おおどりゅう"], kings: ["グノスター"], resistanceIds: ["greatland-dragon"], namelessPossible: true },
    { id: "d2-godskin-duo", name: "神肌の貴種＆神肌の使徒", aliases: ["神肌", "貴種", "使徒"], kings: ["マリス", "リブラ", "カリゴ"], resistanceIds: ["godskin-noble", "godskin-apostle"], namelessPossible: true },
    { id: "d2-fallingstar-beast", name: "降る星の成獣", aliases: ["成獣", "ふるほし"], kings: ["マリス"], resistanceIds: ["fallingstar-beast"], namelessPossible: true },
    { id: "d2-cold-valley-dancer", name: "冷たい谷の踊り子", aliases: ["踊り子", "つめたい谷"], kings: ["カリゴ"], resistanceIds: ["cold-valley-dancer"], namelessPossible: true },
    { id: "d2-nameless-king", name: "無名の王", aliases: ["むめいのおう"], kings: ["フルゴール"], resistanceIds: ["nameless-king-dragon", "nameless-king-human"], namelessPossible: true },
    { id: "d2-death-rite-bird", name: "死儀礼の鳥", aliases: ["しぎれい", "死儀礼"], kings: ["リブラ"], resistanceIds: ["death-rite-bird"], namelessPossible: true },
    { id: "d2-demon-prince", name: "デーモンの王子", aliases: ["王子", "でーもんのおうじ"], kings: ["ハルモニア"], resistanceIds: ["demon-prince"], namelessPossible: false },
    { id: "d2-blood-lord", name: "血の君主", aliases: ["もーぐ様", "モーグ", "ちのくんしゅ"], kings: ["ハルモニア"], resistanceIds: ["blood-lord"], namelessPossible: false },
    { id: "d2-divine-beast", name: "神獣獅子舞", aliases: ["獅子舞", "ししししまい"], kings: ["ストラゲス"], resistanceIds: ["divine-beast-lion"], namelessPossible: false },
    { id: "d2-artorias", name: "騎士アルトリウス", aliases: ["アルトリウス", "artorias"], kings: ["ストラゲス"], resistanceIds: ["artorias"], namelessPossible: false },
    { id: "d2-nameless", name: "該当なし（ナメレス）", aliases: ["ナメレス確定", "該当なし"], kings: ["ナメレス"], resistanceIds: [], namelessPossible: true, noBoss: true }
  ],
  events: [
    { id: "event-margit", name: "忌み鬼", aliases: ["いみおに襲撃"], group: "襲撃イベント", kings: ["エデレ", "グノスター", "ナメレス"] },
    { id: "event-gnoster", name: "知性の蟲", aliases: ["知性の虫"], group: "襲撃イベント", kings: ["マリス", "リブラ", "ナメレス"] },
    { id: "event-malis", name: "兆し", aliases: ["きざし"], group: "襲撃イベント", kings: ["グノスター", "カリゴ", "ナメレス"] },
    { id: "event-libra", name: "調律の魔物", aliases: ["ちょうりつ"], group: "襲撃イベント", kings: ["フルゴール", "リブラ", "カリゴ", "ナメレス"] },
    { id: "event-tricephalos", name: "三つ首の獣", aliases: [], group: "敵の出現情報", kings: ["グラディウス", "エデレ", "グノスター", "マリス", "リブラ", "フルゴール", "カリゴ", "ナメレス", "ハルモニア", "ストラゲス"] },
    { id: "event-caligo", name: "霧の裂け目", aliases: [], group: "敵の出現情報", kings: ["グラディウス", "エデレ", "グノスター", "マリス", "リブラ", "フルゴール", "カリゴ", "ナメレス", "ハルモニア", "ストラゲス"] },
    { id: "event-harmonia", name: "安寧者たち", aliases: ["安寧者"], group: "敵の出現情報", kings: ["グラディウス", "エデレ", "グノスター", "マリス", "リブラ", "フルゴール", "カリゴ", "ナメレス", "ハルモニア", "ストラゲス"] },
    { id: "event-walking-mausoleum", name: "歩く霊廟", aliases: ["霊廟"], group: "突発イベント", kings: ["マリス", "カリゴ"] },
    { id: "event-meteorite", name: "隕石", aliases: ["いんせき"], group: "突発イベント", kings: ["グラディウス", "エデレ", "カリゴ", "ハルモニア"] },
    { id: "event-frenzyflame", name: "狂い火", aliases: ["くるいび"], group: "突発イベント", kings: ["グノスター", "リブラ", "ハルモニア", "ストラゲス"] },
    { id: "event-sorcerertower", name: "古の魔術師塔", aliases: ["魔術師塔"], group: "突発イベント", kings: ["グノスター", "リブラ", "ハルモニア"] },
    { id: "event-nightforce", name: "夜の勢力", aliases: [], group: "突発イベント", kings: ["グラディウス", "マリス", "フルゴール"] },
    { id: "event-new-threat", name: "新たなる脅威", aliases: [], group: "突発イベント", kings: ["エデレ", "フルゴール", "ハルモニア", "ストラゲス"] }
  ],
  namelessDay1Ids: ["d1-demihuman-duo", "d1-bell-bearing-hunter", "d1-devouring-dragon", "d1-night-cavalry", "d1-hero-gargoyle", "d1-wormface", "d1-centipede-demon", "d1-molten-demon", "d1-field-commander", "d1-putrid-tree-spirit", "d1-grafted-lord", "d1-tibia-mariner", "d1-royal-revenant", "d1-public-freyja"],
  namelessDay2Ids: ["d2-tree-guardian", "d2-margit", "d2-ancient-dragon", "d2-crucible-hippo", "d2-roaming-commander", "d2-nox-dragonkin", "d2-dragon-tree-guardian", "d2-greatland-dragon", "d2-godskin-duo", "d2-fallingstar-beast", "d2-cold-valley-dancer", "d2-nameless-king", "d2-death-rite-bird", "d2-nameless"]
});
